export const REPOSITORY = 'https://github.com/yuneco/miracle-pencil'
export const VERSION = '0.0.3'
export const RELEASE_DATE = '2022.01.02'
export const AUTHOR = '@yuneco'
export const AUTHOR_TW = 'https://twitter.com/yuneco'
